---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing
  namespace: landing
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: www.example.com
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: landing-svc
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-svc
                port:
                  name: http
  tls:
    - hosts:
        - example.com
        - www.example.com
      secretName: landing-tls-secret

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing2
  namespace: landing
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # kubernetes.io/ingress.class: nginx
spec:
  # ingressClassName: traefik
  rules:
    - host: www.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: landing-svc
                port:
                  name: http
  tls:
    - hosts:
        - example.com
        - www.example.com
      secretName: landing-tls-secret      

---
apiVersion: v1
kind: Service
metadata:
  name: landing-svc
  namespace: landing
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
