apiVersion: v1
kind: Service
metadata:
  name: app-1
  namespace: argo-test
  labels:
    app: app-1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: node
  selector:
    app: app-1
