apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: sqluser-sample
spec:
  instanceRef:
    name: sqlinstance-sample1
  host: "%"
  password:
    valueFrom:
      secretKeyRef:
        name: sqluser-pass-secret
        key: password