apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  labels:
    app: microservice-blueprint
  name: app-secret
  namespace: microservice-blueprint
spec:
  dataFrom:
  - key: project-dev-app-secret
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secrets
  target:
    name: app-secret